### PR TITLE
Adding CSA Widget for Ressource, Requests, CurrentServices, SubscriptionsByDay

### PR DESCRIPTION
**Pull request by mbettan**
Hello,

Contributing with additional CSA Widgets for HP CSA 4.x. Tested for CSA 4.2 and CSA 4.5.
# Overview
- quotas.html containing the source code in html for the Resource Quota widget
- resources.html containing the source code in html for the Simple Resource Display widget
- requests.html containing the source code in html for the Requests widget
- subscriptionsByDay.html containing the source code in html for the Subscriptions By Day Widget
- currentServices.html containing the source code in html for the Current Services widget
- generic.html containing the source code in html for the Generic widget
- scripts folder containing:
- jquery.flot.js: a JavaScript file needed for the operation of the Resource Quota widget, Subscriptions by Day Widget and the current Services widget.
- jquery.flot.pie.js: a JavaScript file needed for the operation of the Resource Quota widget and the current Services widget.
- jquery.flot.categories.js, jquery.flot.stack.js and jquery.flot.resize.js: three JavaScript files needed for the operation of the Subscriptions by Day Widget.
- quotas folder containing text files needed for the operation of the Resource Quota widget. Each of the text files specifies the quotas for an organization/user. See install steps for more details.
- genericXml folder containing xml files needed for the operation of the Generic widget. See the description of the widget (6.6) for more details. 
- images folder containing images  needed for the operation of the Generic widget. See the description of the widget (6.6) for more details.
# Themes
## Resource Quota widget

This widget shows the resources consumed by the current user logged into CSA, by examining their active online services. The quotas are set in text files and can be system wide, per-organization or per-user. 
ressourcequotas
## Simple Resource Display widget

This widget shows the resources consumed by the current user logged into CSA, almost identical to the quota widget except there is no quota or threshold applied, the values are simply displayed.
ressourceusage
## Requests widget

This widget dynamically shows you the last 4-5 requests you have submitted and their status. It automatically refreshes in the background every 5 seconds so you can see when a request is approved in real time without refreshing the page.
recentrequests
## Subscriptions by Day Widget

This widget dynamically shows you the number of subscriptions made by the current connected user in the last ten days. Only three states are taken into account: TERMINATED, ACTIVE and CANCELLED. The widget automatically refreshes in the background every 5 seconds in real time without refreshing the whole page.
subscriptionsbyday
## Current Services Widget

This widget dynamically shows the distribution of the services of the current connected user based on their states. All 13 possible states are taken into account. The widget automatically refreshes in the background every 5 seconds in real time without refreshing the whole page.

currentservices
## Generic Widget

This widget (above to the left) dynamically parses an xml file (above to the right) and displays all the contained information. In the sample below, the widget retrieves and displays information about a vCenter Server (name, IP address, number of VMs consumed,…). We can imagine OO flows called every hour for example collecting these information and updating it in the xml file. The widget automatically refreshes in the background every 5 seconds in real time without refreshing the whole page. The new information will be then displayed to the user on the MPP almost in real time.
genericwidget
# Installation steps

add_mashup2
Open the HTML file for the widget you want in a text editor, copy and paste the content of the html file into the "Add Mashup Widget" dialog Box in CSA located in Organizations/<organisationName>/Dashboard Widgets.See below:
add_mashup

Some extra files are required for the Quota Widget:
- Create a folder named quotas in the following location: <csa_base_dir>\portal\node_modules\mpp-ui\dist\quotas place the quota text files in this folder. The zip file contains some examples inside the quotas folder.
- quotas\defaults.txt – CSA system wide quota. Must have at least this file in place
- quotas<org_name>.txt – Override quotas for specified CSA organsiation. Ignored if file not found
- quotas<username>.txt – Override quotas for specified user. Ignored if file not found
- Place the two JavaScript files jquery.flot.js and jquery.flot.pie.js found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts
  Some extra files are required for the Subscriptions by Day Widget:
- Place the four JavaScript files jquery.flot.js, jquery.flot.categories.js, jquery.flot.stack.js and jquery.flot.resize.js  found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts

Some extra files are required for the Current Services Widget:
- Place the two JavaScript files jquery.flot.js and jquery.flot.pie.js found in the zip file scripts folder into <csa_base_dir>\portal\node_modules\mpp-ui\dist\scripts
  Some extra files are required for the Generic Widget:
- Create a folder named genericXML in the location:  <csa_base_dir>\portal\node_modules\mpp-ui\dist\genericXML and place the xml file parsed by the widget in this folder. The zip file contains an example genericXML\generic_input.xml
- Create a folder named images where you can add the images to display on the widge. The zip file contains an example images\vmwareLogo.jpg.

Signed-off-by: Michaël Bettan mbe@hpe.com

### CODE REVIEW

**Comment by benc-uk** [comment]
Great idea, thanks for the code. I'll take a proper look over the next few days and merge this in.

**Comment by mbettan** [comment]
Perfect, you can remove your quota widget for my commit. Your code is probably more updated. Thanks

**Comment by benc-uk** [comment]
@mbettan I'm going to merge this pull request and do a bit of tidying up, maybe rename things consistently. I will probably put up a wiki page with the install/usage instructions and other information on it.

BTW - I don't see any quota widget in your commit

**Comment by mbettan** [comment]
@benc-uk Could you rename vcenter-widget as generic-widget ?

This widget load and refresh each 5 seconds an XML file containing some information. vCenter Server is one example, it could be generated by a OO workflows, but it could be SCVMM Azure or whatever.

Thanks

**Comment by benc-uk** [comment]
I've renamed it back to generic

**Pull request merged**
